[package]
name = "dust_vox"
version = "0.1.0"
edition = "2024"

[dependencies]
dust_vdb.workspace = true
dust_pbr.workspace = true
dust_physics.workspace = true
avian3d.workspace = true
pumicite.workspace = true
bevy_pumicite.workspace = true
bevy.workspace = true
dot_vox = "5.1"
thiserror = "1"
rayon = "1.10"
tracing = "0.1"
bitvec = "1"
bytemuck = { version = "1.25", features = ["nightly_float"] }
smallvec = "1.15"
serde = "1"

[dev-dependencies]
dust_physics = { path = "../physics" }
parry3d = { path = "../../../parry/crates/parry3d" }
