load("@crates//:defs.bzl", "all_crate_deps", "aliases")
load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@rules_rust//cargo:defs.bzl", "cargo_toml_env_vars")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "runtime_assets",
    srcs = [
        "//assets:runtime",
        "//crates/pbr/shaders:runtime",
        "//crates/pbr/shaders/sky_atmosphere:runtime",
        "//crates/pbr/shaders/sharc:runtime",
        "//crates/vox/shaders:runtime",
        "@dlss//:dlssd_runtime",
    ],
)

cargo_toml_env_vars(
    name = "cargo_toml_env_vars",
    src = "Cargo.toml",
)

genrule(
    name = "bazel_bin_env",
    outs = ["bazel_bin.env"],
    cmd_bash = "echo 'BAZEL_BIN=$${pwd}/$(BINDIR)' > $@",
    cmd_bat = "@echo BAZEL_BIN=%cd%/$(BINDIR)> $@",
)

rust_binary(
    name = "dust",
    crate_name = "dust",
    crate_root = "src/main.rs",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["Cargo.toml"],
    edition = "2024",
    deps = all_crate_deps(normal = True) + [
        "//crates/vox:dust_vox",
        "//crates/pbr:dust_pbr",
        "//crates/app:dust_app",
        "//crates/denoiser:dust_denoiser",
    ],
    rustc_env_files = [":cargo_toml_env_vars"],
    aliases = aliases(),
    data = [":runtime_assets"],
)
