load("@crates//:defs.bzl", "all_crate_deps", "aliases")
load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@rules_rust//cargo:defs.bzl", "cargo_toml_env_vars")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "runtime_assets",
    srcs = [
        "//crates/pbr/shaders:pbr",
        "//crates/pbr/shaders:pbr_playout",
        "//crates/pbr/shaders:pbr_rtx_pipeline",
        "//crates/pbr/shaders:shadow",
        "//crates/pbr/shaders:shadow_rtx_pipeline",
        "//crates/pbr/shaders:tonemap",
        "//crates/pbr/shaders:tonemap_comp_pipeline",
        "//crates/pbr/shaders/sky_atmosphere:multi_scattering",
        "//crates/pbr/shaders/sky_atmosphere:multi_scattering_comp_pipeline",
        "//crates/pbr/shaders/sky_atmosphere:multi_scattering_layout",
        "//crates/pbr/shaders/sky_atmosphere:sky_view_lut",
        "//crates/pbr/shaders/sky_atmosphere:sky_view_lut_comp_pipeline",
        "//crates/pbr/shaders/sky_atmosphere:sky_view_lut_layout",
        "//crates/pbr/shaders/sky_atmosphere:transmittance_lut",
        "//crates/pbr/shaders/sky_atmosphere:transmittance_lut_comp_pipeline",
        "//crates/pbr/shaders/sky_atmosphere:transmittance_lut_layout",
        "//crates/vox/shaders:blas_builder_copy_coords",
        "//crates/vox/shaders:blas_builder_copy_coords_comp_pipeline",
        "//crates/vox/shaders:blas_builder_copy_coords_playout",
        "//crates/vox/shaders:vox_pbr",
        "//crates/vox/shaders:vox_pbr_rtx_pipeline_library",
        "//crates/vox/shaders:vox_pbr_shadow_pipeline_library",
        "//crates/vox/shaders:vox_shadow",
    ],
)

cargo_toml_env_vars(
    name = "cargo_toml_env_vars",
    src = "Cargo.toml",
)

rust_binary(
    name = "dust",
    crate_name = "dust",
    crate_root = "src/main.rs",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["Cargo.toml"],
    edition = "2024",
    deps = all_crate_deps(normal = True) + [
        "//crates/vox:dust_vox",
        "//crates/pbr:dust_pbr",
    ],
    rustc_env_files = [":cargo_toml_env_vars"],
    aliases = aliases(),
    data = [":runtime_assets"],
)
