[package]
name = "dust"
version = "0.1.0"
edition = "2018"
authors = [
    "Zhixing Zhang <me@neoto.xin>",
    "iMplode nZ <rg@youxplode.com>"
]
categories = ["game-engines", "graphics", "rendering"]
description = "A voxel game engine using Bevy"
exclude = [".github/**/*", "crates/**/*"]
keywords = ["dust-engine", "game", "engine", "gamedev", "graphics", "voxel", "voxel-engine"]
readme = "README.md"

[workspace]
members = ["crates/*"]

[dependencies]
dust-render = { path = "./crates/render" }
dust-core = { path = "./crates/core" }
glam = { version = "0.13", features = ["transform-types"] }

fastnbt = "0.14.0"
fastanvil = "0.14.1"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
default-features = false
features = [
    "bevy_winit",
    "x11"
]

[profile.release]
# lto = "thin"
