[package]
name = "dust-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
dust-render = { path = "crates/render" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_window = { git = "https://github.com/bevyengine/bevy" }
bevy_core = { git = "https://github.com/bevyengine/bevy" }
bevy_transform = { git = "https://github.com/bevyengine/bevy" }
bevy_input = { git = "https://github.com/bevyengine/bevy" }
bevy_winit = { git = "https://github.com/bevyengine/bevy" }


[dev-dependencies]
ash = { version = "0.36", features = ["linked"] }
bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
dustash = { path = "../dustash" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_asset = { git = "https://github.com/bevyengine/bevy" }
tracing-subscriber = "0.3"
