[package]
name = "dust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/*"
]

[dependencies]
dust-sentry = { path = "./crates/sentry", optional = true }

[dev-dependencies]
pin-project = "1.0"
rhyolite = { path = "./crates/rhyolite" }
rhyolite-bevy = { path = "./crates/rhyolite_bevy" }
dust-render = { path = "./crates/render" }
dust-vox = { path = "./crates/vox" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_log = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_window = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_input = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_core = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_winit = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d", features = ["x11", "wayland"] }
bevy_time = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_a11y = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_asset = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_scene = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d", default-features=false }
bevy_diagnostic = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
image = "0.24"
glam = "^0.24"
reqwest = { version = "*", features = ["blocking"] }
smooth-bevy-cameras = { git = "https://github.com/Neo-Zhixing/smooth-bevy-cameras", rev = "2e50cb99547e737713fdded245d3e729b0c73b49" }

[features]
sentry = ["dust-sentry"]
aftermath = ["dust-sentry/aftermath"]

[patch."https://github.com/bevyengine/bevy.git"]
bevy_asset = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_app = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_ecs = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_log = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_window = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_input = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_core = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_hierarchy = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_transform = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_winit = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_time = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_a11y = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_scene = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_diagnostic = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_reflect = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_math = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
bevy_tasks = { git = "https://github.com/dust-engine/bevy.git", branch = "bevy_asset_v2" }
