[package]
name = "dust-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*", "formats/*"]

[dependencies]
dust_render = { path = "crates/render" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_window = { git = "https://github.com/bevyengine/bevy" }
bevy_core = { git = "https://github.com/bevyengine/bevy" }
bevy_transform = { git = "https://github.com/bevyengine/bevy" }
bevy_input = { git = "https://github.com/bevyengine/bevy" }
bevy_winit = { git = "https://github.com/bevyengine/bevy" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
dustash = { path = "../dustash" }
ash = { version = "0.37", features = ["linked"] }


[dev-dependencies]
bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
bevy_asset = { git = "https://github.com/bevyengine/bevy", features=["filesystem_watcher"] }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy" }
tracing-subscriber = "0.3"
dust_format_explicit_aabbs = { path = "formats/explicit_aabbs" }
smooth-bevy-cameras = { git = "https://github.com/Neo-Zhixing/smooth-bevy-cameras" }
glam = "0.21"

[patch."https://github.com/bevyengine/bevy"]
bevy_app = { path = "../bevy/crates/bevy_app" }
bevy_window = { path = "../bevy/crates/bevy_window" }
bevy_core = { path = "../bevy/crates/bevy_core" }
bevy_transform = { path = "../bevy/crates/bevy_transform" }
bevy_input = { path = "../bevy/crates/bevy_input" }
bevy_winit = { path = "../bevy/crates/bevy_winit" }
bevy_ecs = { path = "../bevy/crates/bevy_ecs" }
bevy_asset = { path = "../bevy/crates/bevy_asset" }
bevy_reflect = { path = "../bevy/crates/bevy_reflect" }
bevy_utils = { path = "../bevy/crates/bevy_utils" }
bevy_hierarchy = { path = "../bevy/crates/bevy_hierarchy" }

[profile.profile]
inherits = "release"
debug = true
