[package]
name = "dust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/*"
]

[dependencies]
dust-sentry = { path = "./crates/sentry", optional = true }

[dev-dependencies]
pin-project = "1.0"
rhyolite = { path = "./crates/rhyolite" }
rhyolite-bevy = { path = "./crates/rhyolite_bevy" }
dust-render = { path = "./crates/render" }
dust-vox = { path = "./crates/vox" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_log = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_window = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_input = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_core = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_winit = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d", features = ["x11", "wayland"] }
bevy_time = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_a11y = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
bevy_asset = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d", features = ["filesystem_watcher"] }
bevy_scene = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d", default-features=false }
bevy_diagnostic = { git = "https://github.com/bevyengine/bevy.git", rev = "0c44de76264de79423c0d603d41fd19729b1c27d" }
image = "0.24"
glam = "^0.24"
reqwest = { version = "*", features = ["blocking"] }
smooth-bevy-cameras = { git = "https://github.com/Neo-Zhixing/smooth-bevy-cameras", rev = "bc8e569dd1d06052bb519afc368835733e39088d" }

[features]
sentry = ["dust-sentry"]
aftermath = ["dust-sentry/aftermath"]



[patch."https://github.com/bevyengine/bevy.git"]
bevy_asset = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_app = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_ecs = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_log = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_window = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_input = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_core = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_hierarchy = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_transform = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_winit = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_time = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_a11y = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_scene = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_diagnostic = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_reflect = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_math = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
bevy_tasks = { git = "https://github.com/Neo-Zhixing/bevy", branch = "asset_v2_asset_path_serialization_fix" }
