[package]
name = "dust"
version = "0.1.0"
edition = "2018"
authors = [
    "Zhixing Zhang <me@neoto.xin>",
]
categories = ["game-engines", "graphics", "rendering"]
description = "A large scale voxel rendering framework"
exclude = [".github/**/*", "crates/**/*"]
keywords = ["game", "engine", "gamedev", "graphics", "voxel"]
readme = "README.md"


[workspace]
members = ["crates/*"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
bevy_dust = { path = "./crates/bevy_dust" }
glam = { version = "0.13", features = ["transform-types"] }

fastnbt = "0.14.0"
fastanvil = "0.14.1"
