[package]
name = "dust"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "crates/*",
]

[dependencies]
rhyolite = { path = "../rust-playground" }
bevy_rhyolite = { path = "../rust-playground/crates/bevy" }
dust_vox = { path = "crates/vox" }
dust_pbr = { path = "crates/pbr" }

[dependencies.bevy]
version = "0.17.0-dev"
default-features = false
features = [
    "std",
    "async_executor",
    "bevy_winit",
    "bevy_log",
    "bevy_window",
    "bevy_asset",
    "bevy_scene",
    "debug",
    "reflect_auto_register",
    "multi_threaded",
]

[patch.crates-io]
ash = { git = "https://github.com/PixelDust22/ash.git", branch = "meta" }
bevy_ecs = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_app = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_window = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_platform = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_utils = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_transform = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_time = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_tasks = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_reflect = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_ptr = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_math = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_log = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_input = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_diagnostic = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_derive = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_winit = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_internal = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_asset = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy_scene = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }
bevy = { git = "https://github.com/dust-engine/bevy", branch = "release-0.17.3"  }

[patch."https://github.com/ash-rs/ash.git"]
ash = { git = "https://github.com/PixelDust22/ash", branch = "meta" }

[profile.dev.package.dust-vdb]
opt-level = 3
