[package]
name = "dust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "crates/*",
]


[dependencies]
bevy = { version = "0.13", default-features = false, features = ["bevy_scene"] }
rhyolite = { path = "../rhyolite" }
dust_vox = { path = "./crates/vox" }


[patch.crates-io]
bevy = { path = "../bevy" }
