[package]
name = "dust-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhyolite-bevy = { path = "../rhyolite_bevy" }
rhyolite = { path = "../rhyolite" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_asset = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_math = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
bevy_time = { git = "https://github.com/bevyengine/bevy.git", rev = "527d3a5885daa4b43df7054f7787dad47f06135d" }
once_cell = "1.17"
futures-lite = "1.11"
crossbeam-channel = "^0.5"
pin-project = "1"
tracing = "0.1"
crevice = { git = "https://github.com/LPGhatguy/crevice", features = ["glam"] }
rand = "0.8"
arrayvec = "0.7"

nrd = { path = "C:\\Users\\neo\\Developer\\NRD" }
bytemuck = "1.13"

# Processor dependencies
shaderc = { version = "0.8", optional = true }

[features]
default = ["glsl"]
glsl = ["shaderc"]
