[package]
name = "dust-render"
version = "0.1.0"
authors = ["Zhixing Zhang <me@neoto.xin>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
dust-core = { path = "../core" }
tracing = "*"
raw-window-handle = "*"
glam = { version = "0.13", features = ["transform-types"] }
ash-window = { git = "https://github.com/MaikKlein/ash" }
ash = { git = "https://github.com/MaikKlein/ash" } # wait for 0.33.0 for queue_bind_sparse
vk-mem = { git = "https://github.com/dust-engine/vk-mem-rs" }
image = "0.23.14"
memoffset = "0.6"
log = "*"

[build-dependencies]
shaderc = "0.7"

[lib]
name = "dust_render"
