[package]
name = "dust_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
dustash = { path = "../../../dustash" }
bitflags = "1.3"
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_transform = { git = "https://github.com/bevyengine/bevy" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_asset = { git = "https://github.com/bevyengine/bevy" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
bevy_utils = { git = "https://github.com/bevyengine/bevy" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy" }
ash = { version = "0.37", features = ["linked"] }
glam = "0.21"
num-integer = "0.1.45"

vk-mem = { git = "https://github.com/dust-engine/vk-mem-rs" }

bevy_window = { git = "https://github.com/bevyengine/bevy", optional = true }
bevy_winit = { git = "https://github.com/bevyengine/bevy", optional = true }

futures-util = { version = "0.3", default-features = false, features = ["std"] }
futures-lite = "^1.12"

[features]
swapchain = ["bevy_window", "bevy_winit"]
default = ["swapchain"]
