[package]
name = "dust-render"
version = "0.1.0"
authors = ["Zhixing Zhang <me@neoto.xin>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svo = { path = "../svo" }
block-alloc = { path = "../block_alloc" }
tracing = "*"
raw-window-handle = "*"
glam = { version = "0.13", features = ["transform-types"] }
ash-window = "0.6.0"
ash = "0.32.0"


[build-dependencies]
shaderc = "0.7"

[lib]
name = "dust_render"
