load("@rules_vulkan//vulkan:defs.bzl", "slang_shader")
load("//third_party:slang_playout.bzl", "slang_playout")

package(default_visibility = ["//visibility:public"])

slang_shader(
    name = "blas_builder_copy_coords",
    srcs = ["blas_builder_copy_coords.slang"],
    out = "blas_builder_copy_coords.spv",
    profile = "cs_6_0",
    target = "spirv",
    opts = [
        "-O3",
        "-matrix-layout-row-major",
    ],
)

slang_playout(
    name = "blas_builder_copy_coords_playout",
    srcs = ["blas_builder_copy_coords.slang"],
    out = "blas_builder_copy_coords.playout.bin",
)

slang_shader(
    name = "pbr",
    srcs = ["pbr.slang"],
    out = "pbr.spv",
    profile = "lib_6_3",
    target = "spirv",
    opts = [
        "-O3",
        "-matrix-layout-row-major",
    ],
)

slang_shader(
    name = "shadow",
    srcs = ["shadow.slang"],
    out = "shadow.spv",
    profile = "lib_6_3",
    target = "spirv",
    opts = [
        "-O3",
        "-matrix-layout-row-major",
    ],
)

[genrule(
    name = ron.replace(".", "_"),
    srcs = ["pipeline/" + ron],
    outs = [ron],
    cmd = "cp $< $@",
    cmd_bat = "copy /Y $< $@",
) for ron in [
    "pbr.rtx.pipeline.ron",
    "shadow.rtx.pipeline.ron",
    "blas_builder_copy_coords.comp.pipeline.ron",
]]
