load("@rules_vulkan//vulkan:defs.bzl", "slang_shader")
load("//third_party:pumicite_cli.bzl", "ron2bin", "slang_playout")

package(default_visibility = ["//visibility:public"])

slang_shader(
    name = "sky_atmosphere_module",
    srcs = ["sky_atmosphere.slang"],
    out = "sky_atmosphere.slang-module",
    opts = ["-emit-ir"]
)

slang_shader(
    name = "transmittance_lut",
    srcs = ["transmittance_lut.slang"],
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module"
    ],
    out = "transmittance_lut.spv",
    profile = "cs_6_0",
    target = "spirv",
    opts = ["-O3"],
)
slang_playout(
    name = "transmittance_lut_layout",
    srcs = ["transmittance_lut.slang"],
    out = "transmittance_lut.playout.bin",
    set_attrs = [
        "0:push_descriptor"
    ]
)

slang_shader(
    name = "multi_scattering",
    srcs = ["multi_scattering.slang"],
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module"
    ],
    out = "multi_scattering.spv",
    profile = "cs_6_0",
    target = "spirv",
    opts = ["-O3",],
)
slang_playout(
    name = "multi_scattering_layout",
    srcs = ["multi_scattering.slang"],
    out = "multi_scattering.playout.bin",
    set_attrs = [
        "0:push_descriptor"
    ]
)

slang_shader(
    name = "sky_view_lut",
    srcs = ["sky_view_lut.slang"],
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module"
    ],
    out = "sky_view_lut.spv",
    profile = "cs_6_0",
    target = "spirv",
    opts = ["-O3"],
)
slang_playout(
    name = "sky_view_lut_layout",
    srcs = ["sky_view_lut.slang"],
    out = "sky_view_lut.playout.bin",
    set_attrs = [
        "0:push_descriptor"
    ]
)

ron2bin(
    name = "transmittance_lut_comp_pipeline",
    src = "transmittance_lut.comp.pipeline.ron",
    out = "transmittance_lut.comp.pipeline.bin",
    type = "compute-pipeline",
)

ron2bin(
    name = "multi_scattering_comp_pipeline",
    src = "multi_scattering.comp.pipeline.ron",
    out = "multi_scattering.comp.pipeline.bin",
    type = "compute-pipeline",
)

ron2bin(
    name = "sky_view_lut_comp_pipeline",
    src = "sky_view_lut.comp.pipeline.ron",
    out = "sky_view_lut.comp.pipeline.bin",
    type = "compute-pipeline",
)

filegroup(
    name = "runtime",
    srcs = [
        ":multi_scattering",
        ":multi_scattering_comp_pipeline",
        ":multi_scattering_layout",
        ":sky_view_lut",
        ":sky_view_lut_comp_pipeline",
        ":sky_view_lut_layout",
        ":transmittance_lut",
        ":transmittance_lut_comp_pipeline",
        ":transmittance_lut_layout",
    ],
)
