name: Rust

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - run: sudo apt install libasound2-dev libudev-dev lld
    - name: Detect if formatted
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Lint files
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Install Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libasound2-dev libudev-dev lld
    - name: Attempt build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all-features
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
