[package]
name = "dust_pbr"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.0-dev", default-features = false, features = ["bevy_asset", "bevy_scene", "bevy_color"] }
rhyolite = { path = "../../../rust-playground", features = ["bevy"] }
rhyolite_bevy = { path = "../../../rust-playground/crates/bevy" }
tracing = "0.1"
bytemuck = "1.23"
