[package]
name = "dust_pbr"
version = "0.1.0"
edition = "2021"

[dependencies]
rhyolite = { path = "../../../rhyolite" }
rhyolite_rtx = { path = "../../../rhyolite/crates/rtx" }
bevy = { version = "0.13", default-features = false }
