[package]
name = "dust-core"
version = "0.1.0"
authors = ["Zhixing Zhang <account@neoto.xin>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svo = { path = "../svo" }
