load("@rules_vulkan//vulkan:defs.bzl", "slang_shader")
load("//third_party:pumicite_cli.bzl", "ron2bin", "slang_playout")

package(default_visibility = ["//visibility:public"])

slang_shader(
    name = "pbr_module",
    srcs = ["pbr_common.slang"],
    out = "pbr_common.slang-module",
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module"
    ],
    opts = ["-emit-ir"]
)

slang_playout(
    name = "pbr_module_layout_macro",
    srcs = ["pbr_common.slang"],
    out = "pbr_module_layout.rs",
    format = "codegen",
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module"
    ],
)

slang_shader(
    name = "pbr",
    srcs = ["pbr.slang"],
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module",
        "//crates/pbr/shaders:pbr_module",
    ],
    out = "pbr.spv",
    profile = "lib_6_3",
    target = "spirv",
    opts = [
        "-O3",
        "-matrix-layout-row-major",
    ],
)

slang_shader(
    name = "shadow",
    srcs = ["shadow.slang"],
    hdrs = [
        "//crates/pbr/shaders/sky_atmosphere:sky_atmosphere_module",
        "//crates/pbr/shaders:pbr_module",
    ],
    out = "shadow.spv",
    profile = "lib_6_3",
    target = "spirv",
    opts = [
        "-O3",
        "-matrix-layout-row-major",
    ],
)

ron2bin(
    name = "pbr_rtx_pipeline",
    src = "pbr.rtx.pipeline.ron",
    out = "pbr.rtx.pipeline.bin",
    type = "raytracing-pipeline",
)

ron2bin(
    name = "pbr_playout",
    src = "pbr.playout.ron",
    out = "pbr.playout.bin",
    type = "pipeline-layout",
)

ron2bin(
    name = "shadow_rtx_pipeline",
    src = "shadow.rtx.pipeline.ron",
    out = "shadow.rtx.pipeline.bin",
    type = "raytracing-pipeline",
)

slang_shader(
    name = "tonemap",
    srcs = ["tonemap.slang"],
    out = "tonemap.spv",
    profile = "cs_6_0",
    target = "spirv",
    opts = ["-O3"],
)

ron2bin(
    name = "tonemap_comp_pipeline",
    src = "tonemap.comp.pipeline.ron",
    out = "tonemap.comp.pipeline.bin",
    type = "compute-pipeline",
)

slang_playout(
    name = "tonemap_layout_macro",
    srcs = ["tonemap.slang"],
    out = "tonemap_layout.rs",
    format = "codegen",
)
slang_playout(
    name = "tonemap_playout",
    srcs = ["tonemap.slang"],
    out = "tonemap.playout.bin",
    set_attrs = [
        "0:push_descriptor"
    ],
    format = "bin",
)
