[package]
name = "dust_vdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "^0.24"
fxhash = "0.2"
nohash = "0.2.0"

[dev-dependencies]
rand = "0.8.5"
